// Generated by https://quicktype.io

import { BasicPageParams, BurnPaginationResult } from '../../model/baseModel';

export interface BurnBookTopicItem {
  id: number;
  oid: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  name: string;
  book_ids: number[];
  cate_id: number;
}

export interface BurnBookTopicUpdate {
  id: number;
  name: string;
  book_ids: number[];
  cate_id: number;
}
export type BurnBookTopicAdd = Omit<BurnBookTopicUpdate, 'id'>;

export type BookTopicParams = Pick<BasicPageParams, 'page'>;

export type BurnBookTopicPageResult = BurnPaginationResult<BurnBookTopicItem>;
