// Generated by https://quicktype.io

export interface BurnDocDetail {
  id: number;
  oid: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  title: string;
  content: string;
  book_id: number;
  gov_banned: boolean;
}
