// Generated by https://quicktype.io

import { BurnPaginationResult } from '../../model/baseModel';

export interface BurnNexpItem {
  id: number;
  name: string;
  cate_id: number;
  cate: BurnNexpCateItem;
}

export interface BurnNexpCateItem {
  id: number;
  oid: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  name: string;
}

export type BurnNexpPageResult = BurnPaginationResult<BurnNexpItem>;

export type BurnNexpCatePageResult = BurnPaginationResult<BurnNexpCateItem>;
